[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  NEXT_PUBLIC_MAIN_CANISTER_ID = "hp6ha-baaaa-aaaad-aaloq-cai"
  NEXT_PUBLIC_ZK_CANISTER_ID = "hi7bu-myaaa-aaaad-aaloa-cai"
  NEXT_PUBLIC_IC_HOST = "https://icp0.io"
  NEXT_PUBLIC_USE_MOCK_DATA = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://ic0.app https://icp0.io; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://ic0.app https://icp0.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://ic0.app https://*.ic0.app https://icp0.io https://*.icp0.io https://*.plugwallet.ooo https://mainnet.plugwallet.ooo wss: blob:;" 