[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[build.environment]
  VITE_MAIN_CANISTER_ID = "hp6ha-baaaa-aaaad-aaloq-cai"
  VITE_ZK_CANISTER_ID = "hi7bu-myaaa-aaaad-aaloa-cai"
  VITE_IC_HOST = "https://ic0.app"
  VITE_USE_MOCK_DATA = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://ic0.app; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://ic0.app; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://ic0.app https://*.ic0.app;" 