[workspace]
members = [
    "zk_canister_v2",
]

[workspace.dependencies]
candid = "0.9.11"
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
serde = { version = "1.0.188", features = ["derive"] }
ic-stable-structures = "0.5.6"
sha2 = "0.10.7"
hex = "0.4.3"
getrandom = { version = "0.2.10", features = ["js"] }

[workspace.package]
version = "0.2.0"
edition = "2021"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'