[package]
name = "zk_canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.7.0"
ic-cdk-macros = "0.6.0"
candid = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.10.0"
hex = "0.4.3" 